/* ── Country data for contact form phone dropdown ── */

const PRIORITY_COUNTRY_NAMES = [
  'United States / Canada',
  'United Kingdom',
  'Australia',
  'New Zealand',
  'Germany',
  'Netherlands',
  'United Arab Emirates',
  'Singapore',
];

/* Sorted A-Z. Priority countries appear here too — buildCountryDropdown() hoists them. */
const COUNTRY_LIST = [
  { flag: '🇦🇫', name: 'Afghanistan',                       dial: '+93',  rule: 'other' },
  { flag: '🇦🇱', name: 'Albania',                           dial: '+355', rule: 'other' },
  { flag: '🇩🇿', name: 'Algeria',                           dial: '+213', rule: 'other' },
  { flag: '🇦🇩', name: 'Andorra',                           dial: '+376', rule: 'other' },
  { flag: '🇦🇴', name: 'Angola',                            dial: '+244', rule: 'other' },
  { flag: '🇦🇬', name: 'Antigua and Barbuda',               dial: '+1',   rule: 'other' },
  { flag: '🇦🇷', name: 'Argentina',                         dial: '+54',  rule: 'other' },
  { flag: '🇦🇲', name: 'Armenia',                           dial: '+374', rule: 'other' },
  { flag: '🇦🇺', name: 'Australia',                         dial: '+61',  rule: 'au'    },
  { flag: '🇦🇹', name: 'Austria',                           dial: '+43',  rule: 'other' },
  { flag: '🇦🇿', name: 'Azerbaijan',                        dial: '+994', rule: 'other' },
  { flag: '🇧🇸', name: 'Bahamas',                           dial: '+1',   rule: 'other' },
  { flag: '🇧🇭', name: 'Bahrain',                           dial: '+973', rule: 'other' },
  { flag: '🇧🇩', name: 'Bangladesh',                        dial: '+880', rule: 'bd'    },
  { flag: '🇧🇧', name: 'Barbados',                          dial: '+1',   rule: 'other' },
  { flag: '🇧🇾', name: 'Belarus',                           dial: '+375', rule: 'other' },
  { flag: '🇧🇪', name: 'Belgium',                           dial: '+32',  rule: 'other' },
  { flag: '🇧🇿', name: 'Belize',                            dial: '+501', rule: 'other' },
  { flag: '🇧🇯', name: 'Benin',                             dial: '+229', rule: 'other' },
  { flag: '🇧🇹', name: 'Bhutan',                            dial: '+975', rule: 'other' },
  { flag: '🇧🇴', name: 'Bolivia',                           dial: '+591', rule: 'other' },
  { flag: '🇧🇦', name: 'Bosnia and Herzegovina',            dial: '+387', rule: 'other' },
  { flag: '🇧🇼', name: 'Botswana',                          dial: '+267', rule: 'other' },
  { flag: '🇧🇷', name: 'Brazil',                            dial: '+55',  rule: 'other' },
  { flag: '🇧🇳', name: 'Brunei',                            dial: '+673', rule: 'other' },
  { flag: '🇧🇬', name: 'Bulgaria',                          dial: '+359', rule: 'other' },
  { flag: '🇧🇫', name: 'Burkina Faso',                      dial: '+226', rule: 'other' },
  { flag: '🇧🇮', name: 'Burundi',                           dial: '+257', rule: 'other' },
  { flag: '🇨🇻', name: 'Cabo Verde',                        dial: '+238', rule: 'other' },
  { flag: '🇰🇭', name: 'Cambodia',                          dial: '+855', rule: 'other' },
  { flag: '🇨🇲', name: 'Cameroon',                          dial: '+237', rule: 'other' },
  { flag: '🇨🇫', name: 'Central African Republic',          dial: '+236', rule: 'other' },
  { flag: '🇹🇩', name: 'Chad',                              dial: '+235', rule: 'other' },
  { flag: '🇨🇱', name: 'Chile',                             dial: '+56',  rule: 'other' },
  { flag: '🇨🇳', name: 'China',                             dial: '+86',  rule: 'other' },
  { flag: '🇨🇴', name: 'Colombia',                          dial: '+57',  rule: 'other' },
  { flag: '🇰🇲', name: 'Comoros',                           dial: '+269', rule: 'other' },
  { flag: '🇨🇬', name: 'Congo',                             dial: '+242', rule: 'other' },
  { flag: '🇨🇷', name: 'Costa Rica',                        dial: '+506', rule: 'other' },
  { flag: '🇭🇷', name: 'Croatia',                           dial: '+385', rule: 'other' },
  { flag: '🇨🇺', name: 'Cuba',                              dial: '+53',  rule: 'other' },
  { flag: '🇨🇾', name: 'Cyprus',                            dial: '+357', rule: 'other' },
  { flag: '🇨🇿', name: 'Czech Republic',                    dial: '+420', rule: 'other' },
  { flag: '🇨🇩', name: 'DR Congo',                          dial: '+243', rule: 'other' },
  { flag: '🇩🇰', name: 'Denmark',                           dial: '+45',  rule: 'other' },
  { flag: '🇩🇯', name: 'Djibouti',                          dial: '+253', rule: 'other' },
  { flag: '🇩🇲', name: 'Dominica',                          dial: '+1',   rule: 'other' },
  { flag: '🇩🇴', name: 'Dominican Republic',                dial: '+1',   rule: 'other' },
  { flag: '🇪🇨', name: 'Ecuador',                           dial: '+593', rule: 'other' },
  { flag: '🇪🇬', name: 'Egypt',                             dial: '+20',  rule: 'other' },
  { flag: '🇸🇻', name: 'El Salvador',                       dial: '+503', rule: 'other' },
  { flag: '🇬🇶', name: 'Equatorial Guinea',                 dial: '+240', rule: 'other' },
  { flag: '🇪🇷', name: 'Eritrea',                           dial: '+291', rule: 'other' },
  { flag: '🇪🇪', name: 'Estonia',                           dial: '+372', rule: 'other' },
  { flag: '🇸🇿', name: 'Eswatini',                          dial: '+268', rule: 'other' },
  { flag: '🇪🇹', name: 'Ethiopia',                          dial: '+251', rule: 'other' },
  { flag: '🇫🇯', name: 'Fiji',                              dial: '+679', rule: 'other' },
  { flag: '🇫🇮', name: 'Finland',                           dial: '+358', rule: 'other' },
  { flag: '🇫🇷', name: 'France',                            dial: '+33',  rule: 'other' },
  { flag: '🇬🇦', name: 'Gabon',                             dial: '+241', rule: 'other' },
  { flag: '🇬🇲', name: 'Gambia',                            dial: '+220', rule: 'other' },
  { flag: '🇬🇪', name: 'Georgia',                           dial: '+995', rule: 'other' },
  { flag: '🇩🇪', name: 'Germany',                           dial: '+49',  rule: 'de'    },
  { flag: '🇬🇭', name: 'Ghana',                             dial: '+233', rule: 'other' },
  { flag: '🇬🇷', name: 'Greece',                            dial: '+30',  rule: 'other' },
  { flag: '🇬🇩', name: 'Grenada',                           dial: '+1',   rule: 'other' },
  { flag: '🇬🇹', name: 'Guatemala',                         dial: '+502', rule: 'other' },
  { flag: '🇬🇳', name: 'Guinea',                            dial: '+224', rule: 'other' },
  { flag: '🇬🇼', name: 'Guinea-Bissau',                     dial: '+245', rule: 'other' },
  { flag: '🇬🇾', name: 'Guyana',                            dial: '+592', rule: 'other' },
  { flag: '🇭🇹', name: 'Haiti',                             dial: '+509', rule: 'other' },
  { flag: '🇭🇳', name: 'Honduras',                          dial: '+504', rule: 'other' },
  { flag: '🇭🇺', name: 'Hungary',                           dial: '+36',  rule: 'other' },
  { flag: '🇮🇸', name: 'Iceland',                           dial: '+354', rule: 'other' },
  { flag: '🇮🇳', name: 'India',                             dial: '+91',  rule: 'in'    },
  { flag: '🇮🇩', name: 'Indonesia',                         dial: '+62',  rule: 'other' },
  { flag: '🇮🇷', name: 'Iran',                              dial: '+98',  rule: 'other' },
  { flag: '🇮🇶', name: 'Iraq',                              dial: '+964', rule: 'other' },
  { flag: '🇮🇪', name: 'Ireland',                           dial: '+353', rule: 'other' },
  { flag: '🇮🇱', name: 'Israel',                            dial: '+972', rule: 'other' },
  { flag: '🇮🇹', name: 'Italy',                             dial: '+39',  rule: 'other' },
  { flag: '🇨🇮', name: 'Ivory Coast',                       dial: '+225', rule: 'other' },
  { flag: '🇯🇲', name: 'Jamaica',                           dial: '+1',   rule: 'other' },
  { flag: '🇯🇵', name: 'Japan',                             dial: '+81',  rule: 'other' },
  { flag: '🇯🇴', name: 'Jordan',                            dial: '+962', rule: 'other' },
  { flag: '🇰🇿', name: 'Kazakhstan',                        dial: '+7',   rule: 'other' },
  { flag: '🇰🇪', name: 'Kenya',                             dial: '+254', rule: 'other' },
  { flag: '🇰🇮', name: 'Kiribati',                          dial: '+686', rule: 'other' },
  { flag: '🇽🇰', name: 'Kosovo',                            dial: '+383', rule: 'other' },
  { flag: '🇰🇼', name: 'Kuwait',                            dial: '+965', rule: 'other' },
  { flag: '🇰🇬', name: 'Kyrgyzstan',                        dial: '+996', rule: 'other' },
  { flag: '🇱🇦', name: 'Laos',                              dial: '+856', rule: 'other' },
  { flag: '🇱🇻', name: 'Latvia',                            dial: '+371', rule: 'other' },
  { flag: '🇱🇧', name: 'Lebanon',                           dial: '+961', rule: 'other' },
  { flag: '🇱🇸', name: 'Lesotho',                           dial: '+266', rule: 'other' },
  { flag: '🇱🇷', name: 'Liberia',                           dial: '+231', rule: 'other' },
  { flag: '🇱🇾', name: 'Libya',                             dial: '+218', rule: 'other' },
  { flag: '🇱🇮', name: 'Liechtenstein',                     dial: '+423', rule: 'other' },
  { flag: '🇱🇹', name: 'Lithuania',                         dial: '+370', rule: 'other' },
  { flag: '🇱🇺', name: 'Luxembourg',                        dial: '+352', rule: 'other' },
  { flag: '🇲🇬', name: 'Madagascar',                        dial: '+261', rule: 'other' },
  { flag: '🇲🇼', name: 'Malawi',                            dial: '+265', rule: 'other' },
  { flag: '🇲🇾', name: 'Malaysia',                          dial: '+60',  rule: 'other' },
  { flag: '🇲🇻', name: 'Maldives',                          dial: '+960', rule: 'other' },
  { flag: '🇲🇱', name: 'Mali',                              dial: '+223', rule: 'other' },
  { flag: '🇲🇹', name: 'Malta',                             dial: '+356', rule: 'other' },
  { flag: '🇲🇭', name: 'Marshall Islands',                  dial: '+692', rule: 'other' },
  { flag: '🇲🇷', name: 'Mauritania',                        dial: '+222', rule: 'other' },
  { flag: '🇲🇺', name: 'Mauritius',                         dial: '+230', rule: 'other' },
  { flag: '🇲🇽', name: 'Mexico',                            dial: '+52',  rule: 'other' },
  { flag: '🇫🇲', name: 'Micronesia',                        dial: '+691', rule: 'other' },
  { flag: '🇲🇩', name: 'Moldova',                           dial: '+373', rule: 'other' },
  { flag: '🇲🇨', name: 'Monaco',                            dial: '+377', rule: 'other' },
  { flag: '🇲🇳', name: 'Mongolia',                          dial: '+976', rule: 'other' },
  { flag: '🇲🇪', name: 'Montenegro',                        dial: '+382', rule: 'other' },
  { flag: '🇲🇦', name: 'Morocco',                           dial: '+212', rule: 'other' },
  { flag: '🇲🇿', name: 'Mozambique',                        dial: '+258', rule: 'other' },
  { flag: '🇲🇲', name: 'Myanmar',                           dial: '+95',  rule: 'other' },
  { flag: '🇳🇦', name: 'Namibia',                           dial: '+264', rule: 'other' },
  { flag: '🇳🇷', name: 'Nauru',                             dial: '+674', rule: 'other' },
  { flag: '🇳🇵', name: 'Nepal',                             dial: '+977', rule: 'other' },
  { flag: '🇳🇱', name: 'Netherlands',                       dial: '+31',  rule: 'nl'    },
  { flag: '🇳🇿', name: 'New Zealand',                       dial: '+64',  rule: 'nz'    },
  { flag: '🇳🇮', name: 'Nicaragua',                         dial: '+505', rule: 'other' },
  { flag: '🇳🇪', name: 'Niger',                             dial: '+227', rule: 'other' },
  { flag: '🇳🇬', name: 'Nigeria',                           dial: '+234', rule: 'other' },
  { flag: '🇰🇵', name: 'North Korea',                       dial: '+850', rule: 'other' },
  { flag: '🇲🇰', name: 'North Macedonia',                   dial: '+389', rule: 'other' },
  { flag: '🇳🇴', name: 'Norway',                            dial: '+47',  rule: 'other' },
  { flag: '🇴🇲', name: 'Oman',                              dial: '+968', rule: 'other' },
  { flag: '🇵🇰', name: 'Pakistan',                          dial: '+92',  rule: 'pk'    },
  { flag: '🇵🇼', name: 'Palau',                             dial: '+680', rule: 'other' },
  { flag: '🇵🇸', name: 'Palestine',                         dial: '+970', rule: 'other' },
  { flag: '🇵🇦', name: 'Panama',                            dial: '+507', rule: 'other' },
  { flag: '🇵🇬', name: 'Papua New Guinea',                  dial: '+675', rule: 'other' },
  { flag: '🇵🇾', name: 'Paraguay',                          dial: '+595', rule: 'other' },
  { flag: '🇵🇪', name: 'Peru',                              dial: '+51',  rule: 'other' },
  { flag: '🇵🇭', name: 'Philippines',                       dial: '+63',  rule: 'other' },
  { flag: '🇵🇱', name: 'Poland',                            dial: '+48',  rule: 'other' },
  { flag: '🇵🇹', name: 'Portugal',                          dial: '+351', rule: 'other' },
  { flag: '🇶🇦', name: 'Qatar',                             dial: '+974', rule: 'other' },
  { flag: '🇷🇴', name: 'Romania',                           dial: '+40',  rule: 'other' },
  { flag: '🇷🇺', name: 'Russia',                            dial: '+7',   rule: 'other' },
  { flag: '🇷🇼', name: 'Rwanda',                            dial: '+250', rule: 'other' },
  { flag: '🇰🇳', name: 'Saint Kitts and Nevis',             dial: '+1',   rule: 'other' },
  { flag: '🇱🇨', name: 'Saint Lucia',                       dial: '+1',   rule: 'other' },
  { flag: '🇻🇨', name: 'Saint Vincent and the Grenadines',  dial: '+1',   rule: 'other' },
  { flag: '🇼🇸', name: 'Samoa',                             dial: '+685', rule: 'other' },
  { flag: '🇸🇲', name: 'San Marino',                        dial: '+378', rule: 'other' },
  { flag: '🇸🇹', name: 'São Tomé and Príncipe',             dial: '+239', rule: 'other' },
  { flag: '🇸🇦', name: 'Saudi Arabia',                      dial: '+966', rule: 'sa'    },
  { flag: '🇸🇳', name: 'Senegal',                           dial: '+221', rule: 'other' },
  { flag: '🇷🇸', name: 'Serbia',                            dial: '+381', rule: 'other' },
  { flag: '🇸🇨', name: 'Seychelles',                        dial: '+248', rule: 'other' },
  { flag: '🇸🇱', name: 'Sierra Leone',                      dial: '+232', rule: 'other' },
  { flag: '🇸🇬', name: 'Singapore',                         dial: '+65',  rule: 'sg'    },
  { flag: '🇸🇰', name: 'Slovakia',                          dial: '+421', rule: 'other' },
  { flag: '🇸🇮', name: 'Slovenia',                          dial: '+386', rule: 'other' },
  { flag: '🇸🇧', name: 'Solomon Islands',                   dial: '+677', rule: 'other' },
  { flag: '🇸🇴', name: 'Somalia',                           dial: '+252', rule: 'other' },
  { flag: '🇿🇦', name: 'South Africa',                      dial: '+27',  rule: 'other' },
  { flag: '🇰🇷', name: 'South Korea',                       dial: '+82',  rule: 'other' },
  { flag: '🇸🇸', name: 'South Sudan',                       dial: '+211', rule: 'other' },
  { flag: '🇪🇸', name: 'Spain',                             dial: '+34',  rule: 'other' },
  { flag: '🇱🇰', name: 'Sri Lanka',                         dial: '+94',  rule: 'other' },
  { flag: '🇸🇩', name: 'Sudan',                             dial: '+249', rule: 'other' },
  { flag: '🇸🇷', name: 'Suriname',                          dial: '+597', rule: 'other' },
  { flag: '🇸🇪', name: 'Sweden',                            dial: '+46',  rule: 'other' },
  { flag: '🇨🇭', name: 'Switzerland',                       dial: '+41',  rule: 'other' },
  { flag: '🇸🇾', name: 'Syria',                             dial: '+963', rule: 'other' },
  { flag: '🇹🇼', name: 'Taiwan',                            dial: '+886', rule: 'other' },
  { flag: '🇹🇯', name: 'Tajikistan',                        dial: '+992', rule: 'other' },
  { flag: '🇹🇿', name: 'Tanzania',                          dial: '+255', rule: 'other' },
  { flag: '🇹🇭', name: 'Thailand',                          dial: '+66',  rule: 'other' },
  { flag: '🇹🇱', name: 'Timor-Leste',                       dial: '+670', rule: 'other' },
  { flag: '🇹🇬', name: 'Togo',                              dial: '+228', rule: 'other' },
  { flag: '🇹🇴', name: 'Tonga',                             dial: '+676', rule: 'other' },
  { flag: '🇹🇹', name: 'Trinidad and Tobago',               dial: '+1',   rule: 'other' },
  { flag: '🇹🇳', name: 'Tunisia',                           dial: '+216', rule: 'other' },
  { flag: '🇹🇷', name: 'Turkey',                            dial: '+90',  rule: 'other' },
  { flag: '🇹🇲', name: 'Turkmenistan',                      dial: '+993', rule: 'other' },
  { flag: '🇹🇻', name: 'Tuvalu',                            dial: '+688', rule: 'other' },
  { flag: '🇺🇬', name: 'Uganda',                            dial: '+256', rule: 'other' },
  { flag: '🇺🇦', name: 'Ukraine',                           dial: '+380', rule: 'other' },
  { flag: '🇦🇪', name: 'United Arab Emirates',              dial: '+971', rule: 'ae'    },
  { flag: '🇬🇧', name: 'United Kingdom',                    dial: '+44',  rule: 'uk'    },
  { flag: '🇺🇸', name: 'United States / Canada',            dial: '+1',   rule: 'usca'  },
  { flag: '🇺🇾', name: 'Uruguay',                           dial: '+598', rule: 'other' },
  { flag: '🇺🇿', name: 'Uzbekistan',                        dial: '+998', rule: 'other' },
  { flag: '🇻🇺', name: 'Vanuatu',                           dial: '+678', rule: 'other' },
  { flag: '🇻🇦', name: 'Vatican City',                      dial: '+39',  rule: 'other' },
  { flag: '🇻🇪', name: 'Venezuela',                         dial: '+58',  rule: 'other' },
  { flag: '🇻🇳', name: 'Vietnam',                           dial: '+84',  rule: 'other' },
  { flag: '🇾🇪', name: 'Yemen',                             dial: '+967', rule: 'other' },
  { flag: '🇿🇲', name: 'Zambia',                            dial: '+260', rule: 'other' },
  { flag: '🇿🇼', name: 'Zimbabwe',                          dial: '+263', rule: 'other' },
];
