-- Arrow Atlas, first PostgreSQL schema. Everything a player would be upset to lose lives here.
--
-- Two things drive the shape of this file:
--   * The load test on the SQLite service: every sweep query scanned the whole match history, so a busy lobby
--     got slower every week it ran. Every housekeeping query below is served by a PARTIAL index covering only
--     the handful of rows that are still open or playing, so finished history costs nothing to carry.
--   * The economy must survive a retry. Every movement of gold is a row in gold_ledger with a unique
--     idempotency key, written in the same transaction as the balance change, so paying the same pot twice is
--     not "unlikely", it is rejected by the database.

CREATE TABLE users (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider    TEXT        NOT NULL,
    sub         TEXT        NOT NULL,              -- the provider's opaque id; no email is ever stored
    name        TEXT        NOT NULL DEFAULT '',
    pic         TEXT        NOT NULL DEFAULT '',
    gold        BIGINT      NOT NULL DEFAULT 0 CHECK (gold >= 0),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    seen_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT users_provider_sub_key UNIQUE (provider, sub)
);

-- Sessions are random opaque tokens, kept only as a SHA-256 hash: the database never holds anything that could
-- be replayed if it leaked. The same row backs a browser cookie and a phone's Authorization: Bearer header.
CREATE TABLE sessions (
    token_hash  TEXT        PRIMARY KEY,
    user_id     BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at  TIMESTAMPTZ NOT NULL,
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    client      TEXT        NOT NULL DEFAULT 'web' CHECK (client IN ('web', 'app'))
);
CREATE INDEX sessions_user_idx    ON sessions (user_id);
CREATE INDEX sessions_expires_idx ON sessions (expires_at);

-- A gold match: everyone in the room stakes the same, everyone plays the very same board, and the first to
-- clear it takes the pot.
--
-- stakes_in is the number of stakes actually paid into this room. The pot is stake * stakes_in. It is stored
-- rather than counted from match_players because a player who deletes their account mid-match takes their seat
-- with them, and the winner must still be paid the pot that was actually staked.
CREATE TABLE matches (
    code        TEXT        PRIMARY KEY,
    host_id     BIGINT          NULL REFERENCES users(id) ON DELETE SET NULL,
    stake       BIGINT      NOT NULL CHECK (stake > 0),
    board       TEXT        NOT NULL,
    tier        SMALLINT    NOT NULL DEFAULT 2 CHECK (tier BETWEEN 0 AND 4),
    seed        BIGINT      NOT NULL,
    state       TEXT        NOT NULL CHECK (state IN ('open', 'playing', 'done', 'void')),
    winner_id   BIGINT          NULL REFERENCES users(id) ON DELETE SET NULL,
    open_to_all BOOLEAN     NOT NULL DEFAULT FALSE,
    stakes_in   INTEGER     NOT NULL DEFAULT 0 CHECK (stakes_in >= 0),
    fills_at    TIMESTAMPTZ     NULL,              -- when a room that fills itself starts on its own
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    started_at  TIMESTAMPTZ     NULL,
    settled_at  TIMESTAMPTZ     NULL
);

-- The sweeps. Each one covers only rows in the state it cares about, so 500k finished matches cost nothing.
CREATE INDEX matches_open_idx     ON matches (created_at)         WHERE state = 'open';
CREATE INDEX matches_lobby_idx    ON matches (stake, created_at)  WHERE state = 'open' AND open_to_all;
CREATE INDEX matches_fills_idx    ON matches (fills_at)           WHERE state = 'open' AND fills_at IS NOT NULL;
CREATE INDEX matches_playing_idx  ON matches (created_at)         WHERE state = 'playing';
CREATE INDEX matches_host_idx     ON matches (host_id);
CREATE INDEX matches_winner_idx   ON matches (winner_id);

-- One row per player in a room. seat_id identifies this particular seating, so a player who leaves and comes
-- back produces two distinct stake/refund movements rather than one that collides with itself.
CREATE TABLE match_players (
    seat_id     BIGSERIAL   NOT NULL UNIQUE,
    code        TEXT        NOT NULL REFERENCES matches(code) ON DELETE CASCADE,
    user_id     BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    tier        SMALLINT    NOT NULL DEFAULT 2 CHECK (tier BETWEEN 0 AND 4),
    pct         SMALLINT    NOT NULL DEFAULT 0 CHECK (pct BETWEEN 0 AND 100),
    ms          BIGINT          NULL,              -- the player's own clock; -1 means they ran out of hearts
    finished_at TIMESTAMPTZ     NULL,              -- when the result reached the server: this decides who won
    joined_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (code, user_id)
);
CREATE INDEX match_players_user_idx ON match_players (user_id);
CREATE INDEX match_players_code_idx ON match_players (code, joined_at);

-- Every movement of gold, ever. The balance on users is the running total; this is what it is made of.
--
-- idem_key is the whole point: 'payout:ABC123' can exist at most once, so a settlement that runs twice (a
-- retry, a double-click, two API processes racing) writes the second row into a unique violation and rolls
-- back, leaving the balance untouched. Nothing moves gold except through this table.
CREATE TABLE gold_ledger (
    id          BIGSERIAL   PRIMARY KEY,
    user_id     BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    delta       BIGINT      NOT NULL,
    reason      TEXT        NOT NULL CHECK (reason IN ('signup', 'stake', 'leave_refund', 'expire_refund', 'draw_refund', 'payout', 'admin')),
    match_code  TEXT            NULL,
    idem_key    TEXT        NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT gold_ledger_idem_key UNIQUE (idem_key)
);
CREATE INDEX gold_ledger_user_idx  ON gold_ledger (user_id, created_at DESC);
CREATE INDEX gold_ledger_match_idx ON gold_ledger (match_code) WHERE match_code IS NOT NULL;
